spring.application.name=unidad-abasto-backend
# Configuración de la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/unidad_abasto
spring.datasource.username=postgres
spring.datasource.password=253031
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
